### ISSUE TITLE
it doesn't work!

### ISSUE THREAD

**Issue by Dragut** [axil/import-ipynb#1]
import import_ipynb
import DFATPre
injest()

and I get
importing Jupyter notebook from DFATPre.ipynb
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-9e6f266a00b4> in <module>
      1 import import_ipynb
      2 import DFATPre
----> 3 injest()

NameError: name 'injest' is not defined

**Comment by axil** [comment]
You need to either 
```
from DFATPre import injest
injest()

```
or
```
from DFATPre import *
injest()
```
or
```
import DFATPre
DFATPre.injest()
```
to get it working.
